name: CI

on:
  push:
    branches:
      - "**"

permission:
  contents: read

jobs:

  i18n-lib-test-build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v5
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - name: Install
      run:  npm ci 
    - name: Test
      run: npm run test:coverage
    - name: Build Library
      run: ng build ngx-atomic-i18n

  i18n-demo-test-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v5
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - name: Install
      run:  npm ci
    - name: Build i18n Demo
      run: npm run i18n-build:ngx-i18n-demo && npm run build:ngx-i18n-demo

